# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- feature/azure-pipelines

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install --global workbox-cli
  displayName: 'npm install workbox'

- script: |
    workbox generateSW workbox-config.js
  displayName: 'workbox generate service worker'
  - script: |
  git config --local user.name "Azure Pipelines"
  git config --local user.email "azuredevops@microsoft.com"
  git add .
  git commit -m "Publishing GitHub Pages  ***NO_CI***"
displayName: 'Build and commit pages'

- task: DownloadSecureFile@1
  inputs:
    secureFile: deploy_key
  displayName: 'Get the deploy key'

- script: |
  mkdir ~/.ssh && mv $DOWNLOADSECUREFILE_SECUREFILEPATH ~/.ssh/id_rsa
  chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
  ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  git remote set-url --push origin git@github.com:StruninIhor/struninihor.github.io/homepage.git
  git push origin HEAD:feature/azure-pipelines
displayName: 'Publish GitHub Pages'
condition: |
  and(not(eq(variables['Build.Reason'], 'PullRequest')),
      eq(variables['Build.SourceBranch'], 'refs/heads/feature/azure-pipelines'))